### ISSUE TITLE
test_top_left (tests.api.test_point.PointTest) failed in Firefox

### ISSUE THREAD

**Issue by ftnext** [mherrmann/selenium-python-helium#23]
at master (553bdf2beb2da86d09bf315dc512030159bf7fad )

### expected
all test cases are passed in Firefox

### actual
test_top_left (tests.api.test_point.PointTest) failed in Firefox

```shell
$ TEST_BROWSER=firefox python setup.py test
 :
======================================================================
FAIL: test_top_left (tests.api.test_point.PointTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/.../selenium-python-helium/tests/api/test_point.py", line 17, in test_top_left
    self.assert_is_in_range(
  File "/Users/.../selenium-python-helium/tests/api/test_point.py", line 25, in assert_is_in_range
    self.assert_around(expected_y, y, delta_y)
  File "/Users/.../selenium-python-helium/tests/api/test_point.py", line 27, in assert_around
    self.assertIn(
AssertionError: 8 not found in [2, 3, 4]

----------------------------------------------------------------------
Ran 305 tests in 286.790s

FAILED (failures=1, skipped=2)
```

In Google Chrome, the test case is passed.

```shell
$ python setup.py test
 :
test_top_left (tests.api.test_point.PointTest) ... ok
 :
----------------------------------------------------------------------
Ran 305 tests in 95.053s

OK (skipped=3)
```

### Environments

```shell
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G3020
$ python -V
Python 3.8.1
```

**Comment by mherrmann** [comment]
Thanks! I think I was able to fix this in fafdc4d3b0ae406701e6887a3ab687c5cc08206b. Does it work for you too?

**Comment by ftnext** [comment]
It works for me too.
I ran test cases for Firefox and Chrome at https://github.com/mherrmann/selenium-python-helium/commit/710ac9649ef4c49de8ae414e5d1f599ed526c2a7 (right after https://github.com/mherrmann/selenium-python-helium/commit/fafdc4d3b0ae406701e6887a3ab687c5cc08206b ), and all cases passed 🎉

Thanks!

**Comment by mherrmann** [comment]
Yay! :partying_face:
