### ISSUE TITLE
Running Helium On Docker

### ISSUE THREAD

**Issue by ricardolira** [mherrmann/selenium-python-helium#34]
Hi!
I Tried to run Helium on Docker but I just cannot get it done. I think that this is due to the fact that I cannot parse the chromedriver path. I have a docker container that runs selenium already. I though that by adding chromeOptions just the same would suffice. 
This is the code I have:

```
options = ChromeOptions()
        options.add_argument('--disable-gpu')
        options.add_argument('--disable-impl-side-painting')
        options.add_argument('--disable-gpu-sandbox')
        options.add_argument('--disable-accelerated-2d-canvas')
        options.add_argument('--disable-accelerated-jpeg-decoding')
        dr = he.start_chrome(login_url, headless=True, options=options)
```

Do yo uhave any clue of my problem? 

This is the error I get from Selenium:

```
DriverException('unknown error: Chrome failed to start: crashed\n  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-106-generic x86_64)', None, None)
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
celery_1  |     R = retval = fun(*args, **kwargs)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 632, in __protected_call__
celery_1  |     return self.run(*args, **kwargs)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 463, in run
celery_1  |     return task._orig_run(*args, **kwargs)
celery_1  |   File "/app/worker/views.py", line 56, in run_spyder
celery_1  |     response = spyder.spy()
celery_1  |   File "/app/spyders/TJRJ/spyder.py", line 864, in spy
celery_1  |     params, documents_ids = self.get_entrypoint_documents()
celery_1  |   File "/app/spyders/TJRJ/spyder.py", line 585, in get_entrypoint_documents
celery_1  |     dr = he.start_chrome(login_url, headless=True, options=options)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/helium/__init__.py", line 115, in start_chrome
celery_1  |     return _get_api_impl().start_chrome_impl(url, headless, options)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/helium/_impl/__init__.py", line 102, in start_chrome_impl
celery_1  |     chrome_driver = self._start_chrome_driver(headless, options)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/helium/_impl/__init__.py", line 107, in _start_chrome_driver
celery_1  |     result = Chrome(**kwargs)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
celery_1  |     desired_capabilities=desired_capabilities)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
celery_1  |     self.start_session(capabilities, browser_profile)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
celery_1  |     response = self.execute(Command.NEW_SESSION, parameters)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
celery_1  |     self.error_handler.check_response(response)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
celery_1  |     raise exception_class(message, screen, stacktrace)
celery_1  | selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
celery_1  |   (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-106-generic x86_64)

```

Thanks for any help in advance.

**Comment by mherrmann** [comment]
This is more of a Selenium question than a Helium one. Please ask on StackOverflow.
